basePath: /
info:
  contact: {}
  description: This is Devops API
  title: Swagger Devops API
  version: 0.0.1
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: bearer
    type: apiKey
swagger: "2.0"
